#!/bin/sh
#file : test_cpp.sh

echo "=========================="
echo "Ready make cpp"
echo "=========================="

CPP_OUT=cpp_bin_out

if  g++ -o $CPP_OUT $1 
then 
    echo "./$CPP_OUT"  
	./$CPP_OUT
fi 